# Generated by Django 4.0.4 on 2022-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cutie',
            field=models.CharField(blank=True, choices=[('AUTOMATA', 'AUTOMATA'), ('MANUALA', 'MANUALA')], max_length=45, null=True),
        ),
    ]
