# Generated by Django 4.0.4 on 2022-06-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0001_initial'),
        ('aplicatie1', '0002_car_cutie'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicatie2.location'),
        ),
    ]
